//
// Member.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public class Member: Codable {
    public var name: String?
    public var father: Member?
    public var mother: Member?
    public var spouse: Member?
    
    public init(name: String?, father: Member?, mother: Member?, spouse: Member?) {
        self.name = name
        self.father = father
        self.mother = mother
        self.spouse = spouse
    }
    
    public enum CodingKeys: String, CodingKey {
        case name
        case father
        case mother
        case spouse
    }
}

