//
// Member.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class Member: Codable {

    public var _id: Int?
    public var name: String?
    public var fatherId: Int?
    public var motherId: Int?
    public var spouseId: Int?
    public var father: Member?
    public var mother: Member?
    public var spouse: Member?

    public init(_id: Int?, name: String?, fatherId: Int?, motherId: Int?, spouseId: Int?, father: Member?, mother: Member?, spouse: Member?) {
        self._id = _id
        self.name = name
        self.fatherId = fatherId
        self.motherId = motherId
        self.spouseId = spouseId
        self.father = father
        self.mother = mother
        self.spouse = spouse
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case fatherId = "father_id"
        case motherId = "mother_id"
        case spouseId = "spouse_id"
        case father
        case mother
        case spouse
    }


}

